---
useranalytics_backend_repo: "https://github.com/NikoJunttila/userAnalytics.git"
useranalytics_backend_dest: "/opt/useranalytics-backend"
useranalytics_backend_port: 8000
useranalytics_backend_version: main
