- name: Create node_exporter user
  user:
    name: "{{ node_exporter_user }}"
    shell: /usr/sbin/nologin
    system: yes
    create_home: no

- name: Determine architecture
  set_fact:
    node_exporter_arch: "{{ node_exporter_arch_map[ansible_architecture] }}"

- name: Download node_exporter
  get_url:
    url: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-{{ node_exporter_arch }}.tar.gz"
    dest: /tmp/node_exporter.tar.gz
    mode: "0644"

- name: Extract node_exporter
  unarchive:
    src: /tmp/node_exporter.tar.gz
    dest: /tmp
    remote_src: yes

- name: Install binary
  copy:
    src: "/tmp/node_exporter-{{ node_exporter_version }}.linux-{{ node_exporter_arch }}/node_exporter"
    dest: /usr/local/bin/node_exporter
    owner: "{{ node_exporter_user }}"
    group: "{{ node_exporter_user }}"
    mode: "0755"
    remote_src: yes
  notify: restart node_exporter

- name: Install systemd service
  template:
    src: node_exporter.service.j2
    dest: /etc/systemd/system/node_exporter.service
    mode: "0644"
  notify: restart node_exporter

- name: Enable and start node_exporter
  systemd:
    name: node_exporter
    enabled: yes
    state: started
    daemon_reload: yes

