# Only vps inventory label can access these variables as this is called vps.yml
# Centralized backend IP (e.g., your Raspberry Pi Tailscale IP)
backend_ip: "100.120.189.53"

# VPS Caddy Sites Configuration
# 
# Define all your reverse proxy sites here.
# Each site needs a domain pointing to the VPS public IP in DNS.

caddy_sites:
  - domain: passwords.pi.junttila.dev
    backend: "{{ backend_ip }}:80"
  
  - domain: analytics.pi.junttila.dev
    backend: "{{ backend_ip }}:8102"
  - domain: analytics.junttila.dev  
    backend: "{{ backend_ip }}:8102"

  - domain: bookmarks.pi.junttila.dev  
    backend: "{{ backend_ip }}:8100"
  #analytics backend
  - domain: backend.pi.junttila.dev
    backend: "{{ backend_ip }}:8000"

  - domain: pocket.junttila.dev
    backend: "{{ backend_ip }}:8090"

  - domain: booking.pi.junttila.dev
    backend: "{{ backend_ip }}:5000"

  - domain: booking.junttila.dev
    backend: "{{ backend_ip }}:5000"

  - domain: grafana.junttila.dev
    backend: "{{ backend_ip }}:3222"
