---
# Shiori version
shiori_version: "latest"

# Helper for local access (Podman routes 8080->8080)
shiori_port: 8100

# Basic auth (environment variables for the container)
shiori_admin_username: "admin"
shiori_admin_password: "admin_password"

# Timezone
shiori_timezone: "Europe/Helsinki"
