---
- name: Configure ARM Lab Instance
  hosts: all
  gather_facts: yes
  become: yes

  roles:
    - podman
    - tailscale
    - vaultwarden
    - pihole
    - jellyfin
    - shiori
    - qbittorrent
