$ANSIBLE_VAULT;1.1;AES256
32333430393631396164633935623633393933353462353031656361366133366464376666666462
3161643734373861336638373665633634393633356662390a636362396438613738643031343462
39316638623361386531323161653061666239376162353761393661653035323562386135373132
3664323939633065640a323263633263393633363637336631373762643664383431356134396438
32666436666262633735343466303837643938666366633537353735373636313533346332623937
6231623064303063616266313134326462346163396664306430
