---
useranalytics_svelte_repo: "https://github.com/NikoJunttila/useranalytics-svelte.git"
useranalytics_svelte_dest: "/opt/useranalytics-svelte"
useranalytics_svelte_port: 8102
useranalytics_svelte_container_port: 3000
useranalytics_svelte_version: master

# Environment variables
useranalytics_svelte_node_env: "production"
useranalytics_svelte_public_endpoint: "https://backend.pi.junttila.dev"
useranalytics_svelte_public_internal_endpoint: "http://host.containers.internal:8000"
useranalytics_svelte_public_example_id: "083a1865-fd3a-425c-996c-54fa028b268c"
useranalytics_svelte_public_js_delivr_url: "https://cdn.jsdelivr.net/gh/NikoJunttila/userAnalytics@main/javascript/tracker.js"
